<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class commoditiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("commodities")->insert([
            ['name'=>'Ballast',
            'min_buy'=>1,
            'capacity'=>2,
            'price'=>300,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()], 
            ['name'=>'Drive Speaker',
            'min_buy'=>1,
            'capacity'=>3,
            'price'=>700,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()],
            ['name'=>'Earcup',
            'min_buy'=>10,
            'capacity'=>12,
            'price'=>225,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()],
            ['name'=>'Headband',
            'min_buy'=>2,
            'capacity'=>2,
            'price'=>375,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()],
            ['name'=>'Kipas',
            'min_buy'=>2,
            'capacity'=>2,
            'price'=>150,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()],
            ['name'=>'Lensa',
            'min_buy'=>8,
            'capacity'=>10,
            'price'=>300,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()],
            ['name'=>'Layar',
            'min_buy'=>2,
            'capacity'=>5,
            'price'=>275,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()],
            ['name'=>'Lampu',
            'min_buy'=>2,
            'capacity'=>2,
            'price'=>150,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()],
            ['name'=>'LCD Panel',
            'min_buy'=>2,
            'capacity'=>4,
            'price'=>400,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()],
            ['name'=>'Main Board',
            'min_buy'=>1,
            'capacity'=>5,
            'price'=>700,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()],
            ['name'=>'Microphone',
            'min_buy'=>5, 
            'capacity'=>5,
            'price'=>250,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()],
            ['name'=>'Optical Engine',
            'min_buy'=>1,
            'capacity'=>5,
            'price'=>500,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()],
            ['name'=>'Prosessor',
            'min_buy'=>1,
            'capacity'=>2,
            'price'=>400,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()],
            ['name'=>'Power Supply',
            'min_buy'=>1,
            'capacity'=>5,
            'price'=>500,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()],
            ['name'=>'Sensor Gerak',
            'min_buy'=>2,
            'capacity'=>5,
            'price'=>275,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()],
            ['name'=>'Tracking System',
            'min_buy'=>1,
            'capacity'=>3,
            'price'=>500,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()],
            ['name'=>'Wireless Connecting',
            'min_buy'=>1,
            'capacity'=>3,
            'price'=>600,
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now()]
        ]);
    }
}
