<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class TupalQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tupal_questions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'question' => 'Hari Lahir TNI diperingati pada tanggal…',
                'img_name' => '',
                'answer' => 'd',
                'a' => '29-Apr',
                'b' => '1 Juli',
                'c' => '1 Oktober',
                'd' => '5 Oktober',
                'e' => '10-Nov',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'question' => 'Kapan Tugu Pahlawan diresmikan?',
                'img_name' => '',
                'answer' => 'e',
                'a' => '10-Nov-48',
                'b' => '10-Nov-49',
                'c' => '10-Nov-50',
                'd' => '10-Nov-51',
                'e' => '10-Nov-52',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'question' => 'Siapakah ketua proyek pembangunan Tugu Pahlawan?',
                'img_name' => '',
                'answer' => 'a',
                'a' => 'R. Moestajab Soemowidigdo',
                'b' => 'Ir. Ibrahim Sucahyo',
                'c' => 'Soebangun',
                'd' => 'Ir. Abdul Kadir',
                'e' => 'Ir. Soeratmoko',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'question' => 'Rumah Sakit Simpang adalah salah satu rumah sakit tertua di Surabaya, rumah sakit ini dibangun pada tahun …',
                'img_name' => '',
                'answer' => 'b',
                'a' => '1802',
                'b' => '1808',
                'c' => '1843',
                'd' => '1900',
                'e' => '1907',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'question' => 'Hasil sidang PPKI di Jakarta, menghasilkan keputusan untuk membentuk KNI di seluruh Indonesia, pembentukan KNI di Surabaya dilakukan di … ',
                'img_name' => '',
                'answer' => 'd',
                'a' => 'Gedung BFO',
                'b' => 'Gedung Internatio',
                'c' => 'Hotel Des Indes',
                'd' => 'Gedung Nasional Indonesia',
                'e' => 'Hotel Yamato',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'question' => 'Penyerbuan markas Kempetai di Surabaya dilakukan pada tanggal…',
                'img_name' => '',
                'answer' => 'a',
                'a' => '1 Oktober 1945',
                'b' => '3 Oktober 1945',
                'c' => '13 Oktober 1945',
                'd' => '21 Oktober 1945',
                'e' => '23 Oktober 1945',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'question' => 'Apa merek mesin ketik peninggalan kolonial Belanda yang terdapat pada museum?',
                'img_name' => '',
                'answer' => 'd',
                'a' => 'Remington',
                'b' => 'Royal',
                'c' => 'Olivetti',
                'd' => 'Underwood',
                'e' => 'Arori',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'question' => 'Pertempuran di kantor pos Kebonrojo terjadi selama berapa hari?',
                'img_name' => '',
                'answer' => 'c',
                'a' => '1 Hari',
                'b' => '2 Hari',
                'c' => '3 Hari',
                'd' => '4 Hari',
                'e' => '5 Hari',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'question' => 'Pada tanggal berapakah Brigadir A.W.S Mallaby tiba di pelabuhan Tanjung Perak?',
                'img_name' => '',
                'answer' => 'e',
                'a' => '21 Oktober 1945',
                'b' => '22 Oktober 1945',
                'c' => '23 Oktober 1945',
                'd' => '24 Oktober 1945',
                'e' => '25 Oktober 1945',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'question' => 'Pada awalnya markas Kempetai adalah markas milik…',
                'img_name' => '',
                'answer' => 'a',
                'a' => 'Jepang',
                'b' => 'Inggris',
                'c' => 'Belanda',
                'd' => 'Prancis',
                'e' => 'Portugis',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'question' => 'Apakah nama gedung ini?',
                'img_name' => '11.jpg',
                'answer' => 'b',
                'a' => 'Handelstraat',
                'b' => 'Siola',
                'c' => 'Pecinan',
                'd' => 'Lendeteves',
                'e' => 'Internatio',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'question' => 'Apakah nama tempat ini?',
                'img_name' => '12.jpg',
                'answer' => 'e',
                'a' => 'Gedung Internatio',
                'b' => 'Hotel Orantje',
                'c' => 'Gedung Bank Tabungan',
                'd' => 'Gedung Centrale Burgerlijke Ziekeninrichting',
                'e' => 'Stasiun Semut',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'question' => 'Siapakah nama gambar tokoh pahlawan diatas?',
                'img_name' => '13.jpg',
                'answer' => 'c',
                'a' => 'HR Muhammad',
                'b' => 'Residen Soedirman',
                'c' => 'Drs. Mohammad Hatta',
                'd' => 'Ir. Soekarno',
                'e' => 'Iswahyudi',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'question' => 'How long did the Battle of Surabaya last?',
                'img_name' => '',
                'answer' => 'a',
                'a' => '21 days',
                'b' => '22 days',
                'c' => '23 days',
                'd' => '24 days',
                'e' => '25 days',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'question' => 'Peletakan batu pertama Tugu Pahlawan dilakukan oleh…',
                'img_name' => '',
                'answer' => 'e',
                'a' => 'R. Moestajab Soemowidigdo',
                'b' => 'Drs. Mohammad Hatta',
                'c' => 'HR Muhammad',
                'd' => 'Gubernur Suryo',
                'e' => 'Ir. Soekarno',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'question' => 'Kabupaten manakah yang digunakan sebagai kantor Dewan Perjoeangan Rakyat Indonesia pada  masa pertempuran?',
                'img_name' => '',
                'answer' => 'a',
                'a' => 'Kabupaten Mojokerto',
                'b' => 'Kabupaten Sidoarjo',
                'c' => 'Kabupaten Gresik',
                'd' => 'Kabupaten Lamongan',
                'e' => 'Kabupaten Jombang',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'question' => 'Berapakah tinggi Tugu Pahlawan?',
                'img_name' => '',
                'answer' => 'c',
                'a' => '40 Yard',
                'b' => '40 Meter',
                'c' => '45 Yard',
                'd' => '45 Meter',
                'e' => 'Tidak ada jawaban yang benar',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'question' => '“Beri aku ……., niscaya akan kucabut semeru dari akarnya. Beri aku …… niscaya akan ku guncangkan dunia.”',
                'img_name' => '',
                'answer' => 'c',
                'a' => '100 Pemuda, 10 Orang tua',
                'b' => '100 Orang tua, 100 Pemuda',
                'c' => '1000 Orang tua, 10 Pemuda',
                'd' => '10 Pemuda, 1000 Pemuda',
                'e' => 'Tidak ada jawaban yang benar',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'question' => 'Berapakah jumlah halaman catatan harian Bung Tomo?',
                'img_name' => '',
                'answer' => 'b',
                'a' => '116 Halaman',
                'b' => '118 Halaman',
                'c' => '120 Halaman',
                'd' => '122 Halaman',
                'e' => '124 Halaman',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'question' => 'Pada saat menghadiri kongres BPRI di kota Blitar, Bung Tomo mendapat suvenir berupa…',
                'img_name' => '',
                'answer' => 'a',
                'a' => 'Gelas',
                'b' => 'Perangko',
                'c' => 'Mata Uang Koin',
                'd' => 'Radio',
                'e' => 'Mobil',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'question' => 'Bentuk perjuangan pada masa pertempuran 10 November 1945 tidak hanya dilakukan di garis depan medan pertempuran, perjuangan juga dilakukan oleh para wanita dengan mendirikan markas dapur umum. Di Surabaya, markas dapur umum didirikan pertama kali di …',
                'img_name' => '',
                'answer' => 'e',
                'a' => 'Jalan Tunjungan',
                'b' => 'Jalan Gemblongan',
                'c' => 'Jalan Indrapura',
                'd' => 'Jalan Blauran',
                'e' => 'Jalan Jagalan',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'question' => 'Rumah Sakit Simpang adalah salah satu rumah sakit tertua di Surabaya, rumah sakit ini dibangun atas perintah…',
                'img_name' => '',
                'answer' => 'd',
                'a' => 'Gubernur Suryo',
                'b' => 'Drs. Mohammad Hatta',
                'c' => 'Brigadir Mallaby',
                'd' => 'Gubernur Jendral Daendels',
                'e' => 'Doel Arnowo',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'question' => 'Apa nama surat kabar yang menerbitkan berita proklamasi kemerdekaan Indonesia?',
                'img_name' => '',
                'answer' => 'd',
                'a' => 'Kedaulatan Rakyat',
                'b' => 'Asia Baru',
                'c' => 'Soeara Indonesia',
                'd' => 'Suara Asia',
                'e' => 'Pikiran Rakyat',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'question' => 'Apa merk handycam kuno yang terdapat pada museum?',
                'img_name' => '',
                'answer' => 'b',
                'a' => 'Ensign Ful-Vue',
                'b' => 'Filmo',
                'c' => 'Olivetti',
                'd' => 'Remington',
                'e' => 'Touse',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'question' => 'Salah satu orang yang berkontribusi dalam pembangunan proyek tugu pahlawan adalah Ir. Soeratmoko, bentuk kontribusi beliau yaitu…',
                'img_name' => '',
                'answer' => 'e',
                'a' => 'Sebagai ketua proyek pembangunan',
                'b' => 'Sebagai manager proyek pembangunan',
                'c' => 'Sebagai donatur dalam proyek pembangunan',
                'd' => 'Sebagai pengawas dalam proyek pembangunan',
                'e' => 'Sebagai perancang desain tugu pahlawan',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'question' => 'Apa merek sepeda yang terdapat pada museum?',
                'img_name' => '',
                'answer' => 'c',
                'a' => 'Ensign Ful-Vue',
                'b' => 'Filmo',
                'c' => 'Gazelle',
                'd' => 'Underwood',
                'e' => 'Arori',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'question' => 'Salah satu tokoh pejuang dalam perjuangan revolusi Surabaya 1945 yang menjabat sebagai bendahara BKR, anggota kontak Biro, dan menjadi pimpinan dewan pertahanan rakyat Indonesia yaitu…',
                'img_name' => '',
                'answer' => 'a',
                'a' => 'HR Muhammad Mangundiprojo',
                'b' => 'Residen Soedirman',
                'c' => 'Ir. Ibrahim Sucahyo',
                'd' => 'R. Moestajab Soemowidigdo',
                'e' => 'Ahmad Yani',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'question' => 'Berapa total biaya pada tahun 1952 yang dibutuhkan untuk pembangunan Tugu Pahlawan?',
                'img_name' => '',
                'answer' => 'c',
                'a' => 'Rp 303.100',
                'b' => 'Rp 318.200',
                'c' => 'Rp 323.100',
                'd' => 'Rp 338.200',
                'e' => 'Rp 343.200',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'question' => 'Helm ini digunakan oleh tentara…',
                'img_name' => '29.jpg',
                'answer' => 'c',
                'a' => 'Belanda',
                'b' => 'Jepang',
                'c' => 'Inggris',
                'd' => 'Prancis',
                'e' => 'Portugis',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'question' => 'Salah satu senjata tradisional yang digunakan oleh pejuang Indonesia dalam pertempuran Surabaya yang saat ini dijadikan monumen pada jalan Panglima Sudirman yaitu…',
                'img_name' => '',
                'answer' => 'b',
                'a' => 'Keris',
                'b' => 'Bambu runcing',
                'c' => 'Ketapel',
                'd' => 'Golok',
                'e' => 'Tombak',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'question' => 'Pada masa pertempuran 10 November 1945, para wanita remaja maupun dewasa bertugas untuk menyiapkan makanan dan minuman bagi para pejuang. Siapa nama pelopor dapur umum?',
                'img_name' => '',
                'answer' => 'c',
                'a' => 'Suliha',
                'b' => 'Loekitaningsih',
                'c' => 'S. Dariah',
                'd' => 'Isbandijah',
                'e' => 'Dr. Agusni',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'question' => 'Hario Kecik merupakan pemimpin Polisi Tentara Keamanan Rakyat pascakemerdekaan. Jenis pistol apakah yang digunakan oleh beliau untuk melawan tentara Inggris pada pertempuran Surabaya?',
                'img_name' => '',
                'answer' => 'd',
                'a' => 'Ensign  Ful-Vue',
                'b' => 'Gurkha',
                'c' => 'Gazelle',
                'd' => 'Mausser Parabellum',
                'e' => 'Pyropenik MK I',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'question' => 'Apa nama pulau yang terletak di perairan antara Surabaya, Gresik, dan Pulau Madura?',
                'img_name' => '',
                'answer' => 'a',
                'a' => 'Pulau Nyamukan',
                'b' => 'Pulau Kalosot',
                'c' => 'Pulau Sibandang',
                'd' => 'Pulau Pasi',
                'e' => 'Pulau Kangean',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'question' => 'Apa nama gedung yang terdapat dalam foto tersebut?',
                'img_name' => '34.jpg',
                'answer' => 'e',
                'a' => 'Gedung Centrale Burgerlijke Ziekeninrichting',
                'b' => 'Gedung Internatio',
                'c' => 'Rumah Sakit Darmo',
                'd' => 'Rumah Sakit Simpang',
                'e' => 'Kantor pos Kebonrojo',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'question' => 'Berapa berat granat tangan British WW2 no. 36 Mills Bombs MK 1?',
                'img_name' => '',
                'answer' => 'd',
                'a' => '675 gr',
                'b' => '768 gr',
                'c' => '694 gr',
                'd' => '765 gr',
                'e' => '698 gr',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'question' => 'Dimanakah senapan Steyr Mannlicher ditemukan?',
                'img_name' => '',
                'answer' => 'a',
                'a' => 'Mojokerto',
                'b' => 'Sidoarjo',
                'c' => 'Gresik',
                'd' => 'Tanjung Perak',
                'e' => 'Rumah Sakit Simpang',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'question' => 'Pada tahun berapa lampu senter Philips Knijpkat type 7424-03 dibuat?',
                'img_name' => '',
                'answer' => 'c',
                'a' => '1944',
                'b' => '1933',
                'c' => '1941',
                'd' => '1945',
                'e' => '1937',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'question' => 'Pada tanggal berapa Brigadir Jenderal AWS Mallaby tewas terbunuh?',
                'img_name' => '',
                'answer' => 'b',
                'a' => '27 Oktober 1945',
                'b' => '30 Oktober 1945',
                'c' => '5-Nov-45',
                'd' => '1-Nov-45',
                'e' => '31 Oktober 1945',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'question' => 'Setelah dilakukan proklamasi, Jepang berusaha mencegah tersebarnya berita proklamasi. Apa yang dilakukan oleh media massa untuk mengakali hal tersebut?',
                'img_name' => '',
                'answer' => 'a',
                'a' => 'Menyamarkan teks proklamasi dengan bahasa daerah',
                'b' => 'Menyebarkan berita secara diam-diam',
                'c' => 'Menyebarkan berita di depan umum',
                'd' => 'Menyiarkan teks proklamasi melalui radio lokal',
                'e' => 'Menyamarkan teks proklamasi menjadi sandi morse',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'question' => 'Istilah apa yang digunakan untuk menyebut badan sensor dalam bahasa Jepang?',
                'img_name' => '',
                'answer' => 'c',
                'a' => 'Boeitai',
                'b' => 'Johobu',
                'c' => 'Hodokan',
                'd' => 'Keimpeiho',
                'e' => 'Cuo Seinen Kunrensyo',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'question' => 'Pada 10 November 1945, pemuda Surabaya menghadapi serangan tentara Inggris. Apa nama kapal yang membombardir Kota Surabaya dan memiliki nomor 007 pada bagian lambung kapal? ',
                'img_name' => '',
                'answer' => 'd',
                'a' => 'HMS Carron',
                'b' => 'Underwood',
                'c' => 'Opel Kapitan',
                'd' => 'Hermagesty\'s Ship Caesar',
                'e' => 'Stuart',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'question' => 'Pada tanggal berapa peristiwa perobekan bendera Belanda di hotel Yamato terjadi?',
                'img_name' => '',
                'answer' => 'c',
                'a' => '10-Nov-45',
                'b' => '25 Oktober 1945',
                'c' => '19-Sep-45',
                'd' => '31 September 1945',
                'e' => '1 Oktober 1945',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'question' => 'Istilah pada jaman penjajahan Jepang untuk menyebut wakil residen adalah…',
                'img_name' => '',
                'answer' => 'd',
                'a' => 'Daidanki',
                'b' => 'Johobu',
                'c' => 'Keisatsu',
                'd' => 'Fuku Syucokan',
                'e' => 'Cuo Seinen Kunrensyo',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'question' => 'Dimanakah markas kempetai?',
                'img_name' => '',
                'answer' => 'b',
                'a' => 'Jalan Jayangrono',
                'b' => 'Tugu Pahlawan',
                'c' => 'Gedung nasional Bubutan',
                'd' => 'Tanjung Perak',
                'e' => 'Rumah Sakit Darmo',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'question' => 'Apa itu kempetai? ',
                'img_name' => '',
                'answer' => 'b',
                'a' => 'Perawat',
                'b' => 'Polisi militer',
                'c' => 'Angkatan laut',
                'd' => 'Organisasi pertahanan sipil',
                'e' => 'Pasukan bunuh diri',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'question' => 'Pada perundingan Soekarno - Hawthorn, dibentuk sebuah badan bernama Kontak Biro. Apa tujuan dibentuknya Kontak Biro? ',
                'img_name' => '',
                'answer' => 'a',
                'a' => 'Menghindari bentrokan senjata',
                'b' => 'Melucuti tentara sekutu',
                'c' => 'Memukul mundur tentara Inggris',
                'd' => 'Mempertahankan diri dan senjata hasil rampasan dari tentara sekutu',
                'e' => 'Mempersiapkan pertempuan dengan tentara sekutu',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'question' => 'Pada tanggal 9 November 1945, pemimpin pemerintahan, pemuda, dan badan perjuangan di Surabaya mendapatkan ultimatum dari tentara Inggris untuk menyerahkan diri dan senjata yang dimiliki hingga keesokan harinya pukul 18.00. Siapa nama tentara Inggris yang ',
                'img_name' => '',
                'answer' => 'e',
                'a' => 'Mr. W. V. Ch. Ploegman',
                'b' => 'Mayor Jenderal Hawthorn',
                'c' => 'Kolonel Pugh',
                'd' => 'Jhr. C.H.A. van der Wijck',
                'e' => 'Jenderal Mansergh',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'question' => 'Pada pertempuran 3 hari di kantor pos Kebonrojo, TKR dan Laskar Pemuda Surabaya berhasil memukul mundur dan menjepit pasukan Inggris. Siapa nama pimpinan tentara Inggris yang meminta bantuan presiden Republik Indonesia untuk menghentikan pertempuran? ',
                'img_name' => '',
                'answer' => 'c',
                'a' => 'S. Van Deventer',
                'b' => 'Mr. W. V. Ch. Ploegman',
                'c' => 'Mayor Jenderal Hawthorn',
                'd' => 'Jhr. C.H.A. van der Wijck',
                'e' => 'Robert Guy Loder Symond',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'question' => 'Pada tanggal berapa pertempuran di kantor pos Kebonrojo berlangsung?',
                'img_name' => '',
                'answer' => 'd',
                'a' => '3-5 November 1945',
                'b' => '15-18 Oktober 1945',
                'c' => '1-3 November 1945',
                'd' => '27-29 Oktober 1945',
                'e' => '29 Oktober-1 November 1945',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'question' => 'Siapa yang memberikan radio kepada Bung Tomo sebagai apresiasi dan kenang-kenangan?',
                'img_name' => '',
                'answer' => 'a',
                'a' => 'Bapak Achmad',
                'b' => 'Mas Isman',
                'c' => 'Isbandijah',
                'd' => 'Soetjipto Danoekoesoemo',
                'e' => 'Isaedris',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'question' => 'Siapakah nama gubernur pertama Jawa Timur?',
                'img_name' => '',
                'answer' => 'a',
                'a' => 'Soerjo',
                'b' => 'Doel Arnowo',
                'c' => 'M. Jasin',
                'd' => 'HR Mohamad Mangoendiprodjo',
                'e' => 'R. Moestajab Soemowidigdo',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'question' => 'Buatan negara manakah meriam PSU 40 mm?',
                'img_name' => '',
                'answer' => 'b',
                'a' => 'Norwegia',
                'b' => 'Swedia',
                'c' => 'Finlandia',
                'd' => 'Belanda',
                'e' => 'Inggris',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'question' => 'Meriam PSU 40 mm merupakan hasil rampasan dari tangan tentara sekutu pada pertempuran 10 Nopember 1945. Tipe/model apakah meriam tersebut?',
                'img_name' => '',
                'answer' => 'd',
                'a' => 'M 52',
                'b' => 'L 40 BOFORS',
                'c' => 'I 60 BOFORS',
                'd' => 'L 60 BOFORS',
                'e' => 'M 40 BOFORS',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'question' => 'Mortir 120 mm was made in…',
                'img_name' => '',
                'answer' => 'a',
                'a' => 'Yugoslavia',
                'b' => 'Uni Soviet',
                'c' => 'Hungaria',
                'd' => 'Austria',
                'e' => 'Jerman',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'question' => 'What type of Panser which was taken over from The Allied Troops on November 10th 1945?',
                'img_name' => '',
                'answer' => 'e',
                'a' => 'MK-III',
                'b' => 'MK-V',
                'c' => 'MK-I',
                'd' => 'MK-X',
                'e' => 'MK-II',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'question' => 'Siapa nama mantan perwira PETA yang bertemu dengan brigadir Mallaby di Hotel Intenatio?',
                'img_name' => '',
                'answer' => 'b',
                'a' => 'Shodancho Supriyadi',
                'b' => 'R. Muhammad',
                'c' => 'Sutomo',
                'd' => 'M Jasin',
                'e' => 'Ahmad Yani',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'question' => 'Pada tanggal berapa pertemuan R. Muhammad dan Brigadir Mallaby?',
                'img_name' => '',
                'answer' => 'd',
                'a' => '5-Nov-45',
                'b' => '28 Oktober 1945',
                'c' => '30 Oktober 1945',
                'd' => '26 Oktober 1945',
                'e' => '9-Nov-45',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'question' => 'BPRI merupakan sebuah badan perjuangan yang didirikan oleh Bung Tomo pada tanggal 12 Oktober 1945. Apa kepanjangan dari BPRI?',
                'img_name' => '',
                'answer' => 'c',
                'a' => 'Badan Pertempuran Rakyat Indonesia',
                'b' => 'Badan Persiapan Perang Rakyat Indonesia',
                'c' => 'Barisan Pemberontakan Rakyat Indonesia',
                'd' => 'Badan Pemberontakan Rakyat Indonesia',
                'e' => 'Barisan Pembela Rakyat Indonesia',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'question' => 'Siapakah komando BKR Surabaya?',
                'img_name' => '',
                'answer' => 'a',
                'a' => 'Mayjen Soengkono',
                'b' => 'Residen Sudirman',
                'c' => 'R. Muhammad',
                'd' => 'Doel Arnowo',
                'e' => 'Bung Tomo',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'question' => 'Pada tahun berapakah Doel Arnowo menjabat sebagai walikota Surabaya?',
                'img_name' => '',
                'answer' => 'c',
                'a' => '1948',
                'b' => '1949',
                'c' => '1950',
                'd' => '1951',
                'e' => '1952',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'question' => 'KNI merupakan suatu badan yang dibentuk oleh PPKI pada awal masa kemerdekaan untuk membantu presiden dalam menjalankan pemerintahan. Apa kepanjangan dari KNI?',
                'img_name' => '',
                'answer' => 'e',
                'a' => 'Komisi Nasional Indonesia',
                'b' => 'Komite Nasional Indonesia Merdeka',
                'c' => 'Komisi Nasional Indonesia Pusat',
                'd' => 'Komite Nasional Indonesia Pusat',
                'e' => 'Komite Nasional Indonesia',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'question' => 'Perundingan dengan Brigadir Mallaby dilaksanakan di …',
                'img_name' => '',
                'answer' => 'b',
                'a' => 'Gedung BFO',
                'b' => 'Gedung Internatio',
                'c' => 'Hotel Des Indes',
                'd' => 'Gedung Nasional Indonesia',
                'e' => 'Hotel Yamato',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'question' => 'Mobil Bung Tomo dibuat pada tahun?',
                'img_name' => '',
                'answer' => 'a',
                'a' => '1956',
                'b' => '1957',
                'c' => '1958',
                'd' => '1959',
                'e' => '1960',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'question' => 'Pada pukul berapa Gubernur Soerjo menolak kedatangan sekutu dan menolak ultimatum sekutu pada tanggal 9 Nopember 1945?',
                'img_name' => '',
                'answer' => 'e',
                'a' => 'Pukul 20.30',
                'b' => 'Pukul 20.00',
                'c' => 'Pukul 19.00',
                'd' => 'Pukul 19.30',
                'e' => 'Pukul 21.00',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'question' => 'BKR merupakan badan yang bertugas untuk melakukan pemeliharaan keamanan bersama rakyat dan badan negara yang terbentuk pascakemerdekaan. Alamat-alamat di bawah ini pernah menjadi markas BKR kecuali…',
                'img_name' => '',
                'answer' => 'a',
                'a' => 'Jalan Pregolan no 4',
                'b' => 'Jalan Jayengrono ',
                'c' => 'Jalan Pandean IV',
                'd' => 'Jalan Karet no 7',
                'e' => 'Kampung Tionghoa Slompretan',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'question' => 'Siapa nama kepala karesidenan Surabaya yang turut hadir dalam perundingan dengan Brigadir Mallaby?',
                'img_name' => '',
                'answer' => 'd',
                'a' => 'Jhr. C.H.A. van der Wijck',
                'b' => 'Abdoellah',
                'c' => 'Wahib Wahab',
                'd' => 'Sudirman',
                'e' => 'S. Van Deventer',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'question' => 'Pada 16 Oktober 1945, Bung Tomo mendirikan … di Jalan Mawar untuk menyebarkan semangat perjuangan dan menyatukan rakyat.',
                'img_name' => '',
                'answer' => 'c',
                'a' => 'BPRI',
                'b' => 'BKR',
                'c' => 'Radio Pemberontakan',
                'd' => 'KNI',
                'e' => 'KNIP',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'question' => 'Panzer brend carrier type MK II was made in…',
                'img_name' => '',
                'answer' => 'e',
                'a' => 'Germany',
                'b' => 'Yugoslavia',
                'c' => 'Italy',
                'd' => 'Uni Soviet',
                'e' => 'England',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'question' => 'The Panzer brend carrier was taken over in …',
                'img_name' => '',
                'answer' => 'b',
                'a' => 'Death of Brigadier Mallaby Incident',
                'b' => 'Battle of Surabaya',
                'c' => 'Operation Kraai',
                'd' => 'Yamato Hotel Incident',
                'e' => 'Operation Opossum',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'question' => 'Apakah warna mobil Bung Tomo?',
                'img_name' => '',
                'answer' => 'e',
                'a' => 'Merah',
                'b' => 'Putih',
                'c' => 'Hijau',
                'd' => 'Abu-abu',
                'e' => 'Hitam',
                'point' => 700,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
    }
}
